// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxPtQU-3RIxAKNx_Vmrkvy5hzhKjJ49N4',
    appId: '1:87510516628:web:eec2d9a6685acd438ec581',
    messagingSenderId: '87510516628',
    projectId: 'instagram-tut-8d144',
    authDomain: 'instagram-tut-8d144.firebaseapp.com',
    storageBucket: 'instagram-tut-8d144.appspot.com',
    measurementId: 'G-BCQ3SVW8SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsbr4NfwpAiR463MiinEF1kzjcGzfyNCw',
    appId: '1:87510516628:android:47f59bd61fe5914f8ec581',
    messagingSenderId: '87510516628',
    projectId: 'instagram-tut-8d144',
    storageBucket: 'instagram-tut-8d144.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYJG4j277_mehfU1xmP5we6DkH3FoiYXo',
    appId: '1:87510516628:ios:98997894381b6fee8ec581',
    messagingSenderId: '87510516628',
    projectId: 'instagram-tut-8d144',
    storageBucket: 'instagram-tut-8d144.appspot.com',
    iosClientId: '87510516628-jacsjo52cnom03sdbabnp7d789nbhrsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYJG4j277_mehfU1xmP5we6DkH3FoiYXo',
    appId: '1:87510516628:ios:98997894381b6fee8ec581',
    messagingSenderId: '87510516628',
    projectId: 'instagram-tut-8d144',
    storageBucket: 'instagram-tut-8d144.appspot.com',
    iosClientId: '87510516628-jacsjo52cnom03sdbabnp7d789nbhrsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
